# Generated by Django 4.2.6 on 2023-10-11 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tabulka', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mojetabulka',
            name='age',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='mojetabulka',
            name='post_code',
            field=models.IntegerField(),
        ),
    ]
