# Generated by Django 4.2.6 on 2023-10-11 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tabulka', '0002_alter_mojetabulka_age_alter_mojetabulka_post_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='DalsiTabulka',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pet', models.CharField(max_length=20)),
                ('sex', models.CharField(max_length=10)),
            ],
        ),
    ]
